name: railworks_client
description: Please note that Client for RailWorks is unofficial and not endorsed by Dovetail Games.
version: 0.0.0
homepage: https://github.com/tnc1997/dart-railworks-client

environment:
  sdk: ^2.12.0

dependencies:
  path: ^1.8.0
